name: nonlinear-fit
channels:
- conda-forge
dependencies:
- python=3.11
- scipy=1.10
- cvxpy=1.3
- matplotlib=3.7
- spectral=0.23
- tqdm=4.65
- jupyter
- ray-tune
- ipympl
- imageio
- pip
- pip:
  - pmcx